name: testsnap03
version: '4.0'
summary: Snapcraft simple webserver part
description: |
  You can change the default port (8080) with the -p option, for instance:
  command: webserver -p 9001 www.
grade: stable
confinement: strict

base: core20

parts:
  testsnap03:
    source: github.com/RaschJ/simple-webserver
    source-type: git
    

apps:
    testserver:
      command: usr/local/bin/testserver
      daemon: simple
      restart-condition: always
      plugs: [network-bind]
