name: testsnap03
version: '4.0'
summary: Snapcraft simple webserver part
description: |
  You can change the default port (8080) with the -p option, for instance:
  command: webserver -p 9001 www.
grade: stable
confinement: strict
base: core22

override-build: | craftctl default # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/usr/bin/<snap_name>"

parts:
  testsnap03:
    source: https://github.com/RaschJ/simple-webserver.git
    plugin: go
    build-packages: [git, golang]
    

apps:
    testserver:
      command: testsnap03
      daemon: simple
      restart-condition: always
      plugs: [network-bind]
