name: testsnap03
version: '4.0'
summary: Snapcraft simple webserver part
description: |
  You can change the default port (8080) with the -p option, for instance:
  command: webserver -p 9001 www.
grade: stable
confinement: strict
base: core22

parts:
  testsnap03:
    source: https://github.com/RaschJ/simple-webserver.git
    plugin: go
    build-packages: [git, golang]
    

apps:
    testserver:
      #command: testsnap03
      daemon: simple
      restart-condition: always
      plugs: [network-bind]
