name: testsnap03
version: '4.0'
summary: Snapcraft simple webserver part
description: |
  You can change the default port (8080) with the -p option, for instance:
  command: webserver -p 9001 www.
grade: stable
confinement: strict

parts:
  testsnap03:
    source: .
    plugin: go
    go-importpath: github.com/ubuntu/simple-webserver-part

apps:
    testsnap03:
      command: bin/webserver
      daemon: simple
      restart-condition: always
      plugs: [network-bind]
